name = "JacobiElliptic"
uuid = "2a8b799e-c098-4961-872a-356c768d184c"
authors = ["dominic-chang <dochang@g.harvard.com>"]
version = "0.3.5"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[extensions]
JacobiEllipticEnzymeExt = "Enzyme"
JacobiEllipticForwardDiffExt = "ForwardDiff"
JacobiEllipticZygoteExt = "Zygote"

[compat]
DocStringExtensions = "0.9"
Enzyme = "0.13"
ForwardDiff = "0.10"
StaticArrays = "1.6"
Zygote = "0.6, 0.7"
julia = "1.10"
